// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "0b1e3239-7f03-4f52-8efb-117ee3444098");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1630062716);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1630062836);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1630062236);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1630062476);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1630062356);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1630062596);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1630062956);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1024000);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1630062206);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 77);
user_pref("browser.newtabpage.activity-stream.impressionId", "{16d0116e-e17f-419f-9788-b33f3bae2de2}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1630047600);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1630062244913");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1630064032913");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1630062223943");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1630083823943");
user_pref("browser.search.region", "IN");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1630062217");
user_pref("browser.slowStartup.averageTime", 12936);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20190128144255");
user_pref("browser.startup.homepage_override.mstone", "65.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "65.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "673fc040061b4b2d8e6326d214c7df94");
user_pref("extensions.blocklist.lastModified", "Thu, 08 Jul 2021 21:38:01 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1630062749);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "65.0");
user_pref("extensions.lastPlatformVersion", "65.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"e18014e8-140b-4179-b111-66f22a1a29ae\",\"screenshots@mozilla.org\":\"dff00f10-9306-4d14-b789-d021f06c853f\",\"webcompat-reporter@mozilla.org\":\"5d5ecf74-d675-4465-8bbf-fe3ba10438bb\",\"webcompat@mozilla.org\":\"a1fb62c5-5e8c-4fe5-8da0-b2f9f5684599\",\"baidu-code-update@mozillaonline.com\":\"fdb26ec3-6042-43c2-89d7-6b107412a8d6\",\"fxmonitor@mozilla.org\":\"d8a857ee-54f3-4373-883b-2e44517e1825\"}");
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1630062427);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20190128144255");
user_pref("media.gmp-manager.lastCheck", 1630062424);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "6a06a693-8b7a-4cd3-bdc3-c6626046bc64");
user_pref("security.sandbox.plugin.tempDirSuffix", "4b45c3e9-29b4-4d6a-b76b-36ff9b66222f");
user_pref("services.blocklist.addons.checked", 1630066033);
user_pref("services.blocklist.gfx.checked", 1630066033);
user_pref("services.blocklist.onecrl.checked", 1630066033);
user_pref("services.blocklist.pinning.checked", 1630066033);
user_pref("services.blocklist.plugins.checked", 1630066033);
user_pref("services.settings.clock_skew_seconds", -452);
user_pref("services.settings.last_etag", "\"1630051055608\"");
user_pref("services.settings.last_update_seconds", 1630063048);
user_pref("services.settings.main.language-dictionaries.last_check", 1630066033);
user_pref("services.settings.main.sites-classification.last_check", 1630066033);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1630062199);
user_pref("toolkit.telemetry.cachedClientID", "3da82313-88d8-4fac-8b66-27bdafe528ad");
user_pref("toolkit.telemetry.previousBuildID", "20190128144255");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
